import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import ProtectedRoute from "../components/ProtectedRoute";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Instagram",
  description: "Generated by create next app",
  icons: '/images/logo.png',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <SessionProviderWrapper>
 
          <ProtectedRoute>{children}</ProtectedRoute>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
